### ISSUE TITLE
Instructions on how to play

### ISSUE THREAD

**Issue by sarah2123** [sarah2123/QuizMaster#2]
**User Story:**
As a user, I want to access instructions so that I can understand the rules.

**Acceptance Criteria:**
- [x] Include a "How to Play" Button.
- [x] Clicking the “How to Play” button opens a modal with clear instructions.
- [x] The modal should close when the user clicks outside or on a close button.

**Tasks:**
- [x] Create a "How to Play" button.
- [x] Create a modal that displays instructions when “How to Play” is clicked.
- [x] Add functionality to close the modal.
