### ISSUE TITLE
Answer Feedback

### ISSUE THREAD

**Issue by sarah2123** [sarah2123/QuizMaster#8]
**User Story:**
As a user, I want to know if my answer is correct or incorrect immediately so that i know what the correct answer is.

**Acceptance Criteria:**
- [ ] Highlight correct answers in green and incorrect answers in red.
- [ ] Show the correct answer in green if the user’s choice is wrong.

**Tasks:**
- [ ] Implement logic to check the user’s selection.
- [ ] Highlight the selected option based on correctness.
